site_name: Dat Docs
pages:
- [overview.md, Overview]
- [fields.md, Fields]
- [models.md, Models]
- [QuerySets.md, QuerySets]
- [cookbook.md, Cookbook]
- [about.md, About]
- [coming_soon.md, Coming Soon]
theme: readthedocs
